### ISSUE TITLE
Docker not working in branch v1.0-DEV

### ISSUE THREAD

**Issue by bilak** [SPARQL-Anything/sparql.anything#450]
I've tried to build and run the docker image with following steps:

`docker build -f Dockerfile.development -t sparql-anything-development .`
`docker run -v sparql-anything_playwright:/ms-playwright -v sparql-anything_m2:/root/.m2 -p 3000:3000 --rm -it -v `pwd`:/app sparql-anything-development`

however there is some missing/misconfigured class

```
Listening for transport dt_socket at address: 9091
Error: Could not find or load main class io.github.sparqlanything.fuseki.Endpoint
Caused by: java.lang.ClassNotFoundException: io.github.sparqlanything.fuseki.Endpoint
```

**Comment by luigi-asprino** [comment]
The path of the bibliography module was not updated after #445 
This was fixed in `de7daa4`

**Comment by bilak** [comment]
I've just pulled the latest 1.x branch and error is still present.

**Comment by luigi-asprino** [comment]
The version id was not updated in Dockerfile.development
[563108f](https://github.com/SPARQL-Anything/sparql.anything/commit/563108f5b0a6dbe31c8e21b9e3f202e0db4e55bb) should have fixed it.

**Comment by bilak** [comment]
works, thanks!

**Comment by luigi-asprino** [comment]
Great!
